name: hub
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  primary_button: ^0.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.6
  flutter_svg: ^0.19.3
  firebase_auth: ^3.0.2
  google_sign_in: ^5.0.7
  firebase_core: ^1.5.0
  font_awesome_flutter: ^9.1.0
  provider: ^5.0.0
  flutter_swiper: ^1.1.6
  flutter_native_splash: ^0.3.2
  rename: ^1.3.1
flutter_native_splash:
  color: "#FF0000"
  image: assets/splash.png
  android: true
  ios: true

  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"
flutter_icons:
  android: true
  ios: true
  image_path: "icons/hub.jpg"
  


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/hicon.png
     - assets/drewp.jpg
     - assets/home.png
     - assets/apple.svg
     - assets/whatsapp.svg
     - assets/instagram.svg
     - assets/twitter.svg
     - assets/facebook.svg
     - assets/gmail.svg
     - assets/github.svg
     - assets/discord.svg
     - assets/account.svg
     - assets/adduser.svg
     - assets/google.png
     - assets/sports.png
     - assets/food.png
     - assets/health.png
     - assets/photography.png
     - assets/design.png
     - assets/kids.png
     - assets/women.png
     - assets/men.png
     - assets/movie.png
     - assets/knowledge.png
     - assets/browse.png
     - assets/tech.png
     - assets/travel.png
     - assets/shopping.png
     - assets/student.png
     - assets/business.png
     - assets/crown.png
     - assets/drawer.jpg
     - assets/menu.png
     - assets/isports.png
     - assets/ifood.png
     - assets/web.png
     - assets/apple.png
     - assets/play.png
     - assets/ihealth.png
     - assets/ibrowse.png
     - assets/ibus.png
     - assets/ikid.png
     - assets/iknow.png
     - assets/imen.png
     - assets/iwomen.png
     - assets/iphoto.png
     - assets/ishop.png
     - assets/istudent.png
     - assets/itech.png
     - assets/itravel.png
     - assets/imovie.png
     - assets/yt.png
     - assets/sback.jpg
     

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Apple
       fonts:
         - asset: fonts/SF-Pro-Rounded-Medium.otf
         
           
     
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
